version: '3'
services:
  backend:
    image: qnib/plain-influxdb@sha256:2eebe3f013f2093a1db8c0d33e396f74be8ae9bfb72024f28000a07c1aaf3681
    environment:
     - INFLUXDB_DATABASES=qframe
     - INFLUXDB_META_LOGGING=true
    volumes:
     - /opt/influxdb/shared
    ports:
     - 8083:8083
     - 8086:8086

  frontend:
    image: qnib/plain-grafana4:4.4.1.2
    ports:
     - 3000:3000
    environment:
     - INFLUXDB_HOST=tasks.backend
     - INFLUXDB_DB=qframe

